# Explanations and expectations:
# While I do not make any sort of dictionary ordering mandatory, I do think it is nice to generally have
# the top-level entries be sorted in the in-game order, left-to-right, top-to-bottom. This allows for (in my opinion)
# easier-to-follow outputs for the end user when printing final results.
# The value of each top-level key is named in a way I currently find slightly distasteful -
# I have yet to find better options, so what I mean by each and why I chose them is as follows: (Suggestions appreciated!)

# "total points required": int - The classpec talent trees have 3 "tiers" to them. Players are probably implicitly familiar with these.
# The first tier is what you get access to immediately, with no requirements other than maybe pathing.
# The second and third tiers require an increasing amount of points spent to unlock.
# Do all classpecs have 8/20 tier 2/3 breakpoints? I don't know! If they don't, consider this future-proofing against
# this and also possible weirdnesses like "half-tiers" that might get thrown at the wall in a decade.

# "allocated": int - This is only used when actively generating or displaying a random tree. Should always be zero in the default file.
# Offers sort of a short-term 3rd-party future proofing that allows for building a proper talent tree viewer/manager off of this later.

# "max": int - The in-game limit of how many points are possible to allocate to a given talent.

# "unlocks": List[String] - I saw some other early-Dragonflight tools doing fucking *cycle checking?* No. Just no. Don't.
# WoW talent trees do not allow for cyclic graphs. If you're describing anything potentially approaching that, you're doing it wrong.
# Just list all talents that have arrows pointed to them by the talent whose field this is in. Okay, minirant done.
# As noted at the start, I do prefer to match in-game order left-to-right and top-to-bottom.
# It's less notable here though, when we're two levels deep into the data structure.
# Don't try and get fancy and eschew the list if there's just one string. This will cause more headaches and complexity in generator.py

# "locks": String - Talent choice nodes are weird. We don't have to care about that if we're only dealing with text!
# This just pretends they're alongside each other(they kinda are) and gives them a field noting what they're mutually exclusive with.
# Talents are only mutually exclusive with one talent at a time, so this is only a single string.
# If there was mutual exclusivity among a pool of talents, this should be changed to a List[String] and generator.py should be changed accordingly.

# Q: Why the formatting choices?
# A: I just use black and be done with it.

holypriest_class_tree = {
    "Renew": {
        "total points required": 0,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Prayer of Mending", "Improved Flash Heal"],
        "toplevel": True,
        "mandatory": True,
    },
    "Dispel Magic": {
        "total points required": 0,
        "allocated": 1,
        "max": 1,
        "unlocks": [
            "Improved Flash Heal",
            "Improved Purify",
            "Psychic Voice",
            "Petrifying Scream",
        ],
        "toplevel": True,
        "mandatory": False,
    },
    "Shadowfiend": {
        "total points required": 0,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Psychic Voice", "Petrifying Scream", "Shadow Word: Death"],
        "toplevel": True,
        "mandatory": False,
    },
    "Prayer of Mending": {
        "total points required": 0,
        "allocated": 1,
        "max": 1,
        "unlocks": [
            "Focused Mending",
            "Holy Nova",
            "Spell Warding",
            "Blessed Recovery",
        ],
        "parents": ["Renew"],
        "mandatory": True,
    },
    "Improved Flash Heal": {
        "total points required": 0,
        "allocated": 1,
        "max": 1,
        "unlocks": [
            "Holy Nova",
            "Protective Light",
            "From Darkness Comes Light",
            "Angelic Feather",
        ],
        "parents": ["Renew", "Dispel Magic"],
        "mandatory": False,
    },
    "Improved Purify": {
        "total points required": 0,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Angelic Feather"],
        "parents": ["Dispel Magic"],
        "mandatory": False,
    },
    "Psychic Voice": {
        "total points required": 0,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Angelic Feather", "Phantasm"],
        "locks": "Petrifying Scream",
        "parents": ["Dispel Magic", "Shadowfiend"],
        "mandatory": False,
    },
    "Petrifying Scream": {
        "total points required": 0,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Angelic Feather", "Phantasm"],
        "locks": "Psychic Voice",
        "parents": ["Dispel Magic", "Shadowfiend"],
        "mandatory": False,
    },
    "Shadow Word: Death": {
        "total points required": 0,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Phantasm", "Death and Madness"],
        "parents": ["Shadowfiend"],
        "mandatory": False,
    },
    "Focused Mending": {
        "total points required": 0,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Spell Warding", "Blessed Recovery"],
        "parents": ["Prayer of Mending"],
        "mandatory": False,
    },
    "Holy Nova": {
        "total points required": 0,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Spell Warding", "Blessed Recovery", "Rhapsody", "Leap of Faith"],
        "parents": ["Prayer of Mending", "Improved Flash Heal"],
        "mandatory": False,
    },
    "Protective Light": {
        "total points required": 0,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Leap of Faith"],
        "locks": "From Darkness Comes Light",
        "parents": ["Improved Flash Heal"],
        "mandatory": False,
    },
    "From Darkness Comes Light": {
        "total points required": 0,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Leap of Faith"],
        "locks": "Protective Light",
        "parents": ["Improved Flash Heal"],
        "mandatory": False,
    },
    "Angelic Feather": {
        "total points required": 0,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Leap of Faith", "Shackle Undead", "Sheer Terror", "Void Tendrils"],
        "parents": [
            "Improved Flash Heal",
            "Improved Purify",
            "Psychic Voice",
            "Petrifying Scream",
        ],
        "mandatory": False,
    },
    "Phantasm": {
        "total points required": 0,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Sheer Terror", "Void Tendrils", "Mind Control", "Dominate Mind"],
        "parents": ["Psychic Voice", "Petrifying Scream", "Shadow Word: Death"],
        "mandatory": False,
    },
    "Death and Madness": {
        "total points required": 0,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Mind Control", "Dominate Mind", "Tithe Evasion"],
        "parents": ["Shadow Word: Death"],
        "mandatory": False,
    },
    "Spell Warding": {
        "total points required": 0,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Words of the Pious", "Mass Dispel", "Inspiration"],
        "locks": "Blessed Recovery",
        "parents": ["Focused Mending", "Prayer of Mending", "Holy Nova"],
        "mandatory": False,
    },
    "Blessed Recovery": {
        "total points required": 0,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Words of the Pious", "Mass Dispel", "Inspiration"],
        "locks": "Spell Warding",
        "parents": ["Focused Mending", "Prayer of Mending", "Holy Nova"],
        "mandatory": False,
    },
    "Rhapsody": {
        "total points required": 0,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Mass Dispel"],
        "parents": ["Holy Nova"],
        "mandatory": False,
    },
    "Leap of Faith": {
        "total points required": 0,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Mass Dispel", "Move with Grace", "Power Infusion"],
        "parents": [
            "Holy Nova",
            "Protective Light",
            "From Darkness Comes Light",
            "Angelic Feather",
        ],
        "mandatory": False,
    },
    "Shackle Undead": {
        "total points required": 0,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Power Infusion"],
        "parents": ["Angelic Feather"],
        "mandatory": False,
    },
    "Sheer Terror": {
        "total points required": 0,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Power Infusion", "Sanguine Teachings", "Vampiric Embrace"],
        "locks": "Void Tendrils",
        "parents": ["Angelic Feather", "Phantasm"],
        "mandatory": False,
    },
    "Void Tendrils": {
        "total points required": 0,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Power Infusion", "Sanguine Teachings", "Vampiric Embrace"],
        "locks": "Sheer Terror",
        "parents": ["Angelic Feather", "Phantasm"],
        "mandatory": False,
    },
    "Mind Control": {
        "total points required": 0,
        "allocated": 1,
        "max": 1,
        "unlocks": [
            "Sanguine Teachings",
            "Vampiric Embrace",
            "Apathy",
        ],
        "locks": "Dominate Mind",
        "parents": ["Phantasm", "Death and Madness"],
        "mandatory": False,
    },
    "Dominate Mind": {
        "total points required": 0,
        "allocated": 1,
        "max": 1,
        "unlocks": [
            "Sanguine Teachings",
            "Vampiric Embrace",
            "Apathy",
        ],
        "locks": "Mind Control",
        "parents": ["Phantasm", "Death and Madness"],
        "mandatory": False,
    },
    "Words of the Pious": {
        "total points required": 8,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Inspiration"],
        "parents": ["Spell Warding", "Blessed Recovery"],
        "mandatory": False,
    },
    "Mass Dispel": {
        "total points required": 8,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Inspiration", "Mental Agility", "Body and Soul"],
        "parents": ["Spell Warding", "Blessed Recovery", "Rhapsody", "Leap of Faith"],
        "mandatory": False,
    },
    "Move with Grace": {
        "total points required": 8,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Body and Soul"],
        "parents": ["Leap of Faith"],
        "mandatory": False,
    },
    "Power Infusion": {
        "total points required": 8,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Body and Soul", "Twins of the Sun Priestess", "Void Shield"],
        "parents": ["Leap of Faith", "Shackle Undead", "Sheer Terror", "Void Tendrils"],
        "mandatory": False,
    },
    "Sanguine Teachings": {
        "total points required": 8,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Void Shield", "San'layn", "Apathy"],
        "locks": "Vampiric Embrace",
        "parents": ["Sheer Terror", "Void Tendrils", "Mind Control", "Dominate Mind"],
        "mandatory": False,
    },
    "Vampiric Embrace": {
        "total points required": 8,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Void Shield", "San'layn", "Apathy"],
        "locks": "Sanguine Teachings",
        "parents": ["Sheer Terror", "Void Tendrils", "Mind Control", "Dominate Mind"],
        "mandatory": False,
    },
    "Tithe Evasion": {
        "total points required": 8,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Apathy"],
        "parents": ["Death and Madness"],
        "mandatory": False,
    },
    "Inspiration": {
        "total points required": 8,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Unwavering Will"],
        "parents": [
            "Words of the Pious",
            "Spell Warding",
            "Blessed Recovery",
            "Mass Dispel",
        ],
        "mandatory": False,
    },
    "Mental Agility": {
        "total points required": 8,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Unwavering Will"],
        "parents": ["Mass Dispel"],
        "mandatory": False,
    },
    "Body and Soul": {
        "total points required": 8,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Unwavering Will", "Twist of Fate"],
        "parents": ["Mass Dispel", "Move with Grace", "Power Infusion"],
        "mandatory": False,
    },
    "Twins of the Sun Priestess": {
        "total points required": 8,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Twist of Fate"],
        "parents": ["Power Infusion"],
        "mandatory": False,
    },
    "Void Shield": {
        "total points required": 8,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Twist of Fate", "Throes of Pain"],
        "parents": ["Power Infusion", "Sanguine Teachings", "Vampiric Embrace"],
        "mandatory": False,
    },
    "San'layn": {
        "total points required": 8,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Throes of Pain"],
        "parents": ["Sanguine Teachings", "Vampiric Embrace"],
        "mandatory": False,
    },
    "Apathy": {
        "total points required": 8,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Throes of Pain"],
        "parents": ["Tithe Evasion"],
        "mandatory": False,
    },
    "Unwavering Will": {
        "total points required": 8,
        "allocated": 2,
        "max": 2,
        "unlocks": ["Angel's Mercy", "Binding Heals", "Divine Star", "Halo"],
        "parents": ["Inspiration", "Mental Agility", "Body and Soul"],
        "mandatory": False,
    },
    "Twist of Fate": {
        "total points required": 8,
        "allocated": 2,
        "max": 2,
        "unlocks": ["Divine Star", "Halo", "Translucent Image"],
        "parents": ["Body and Soul", "Twins of the Sun Priestess", "Void Shield"],
        "mandatory": False,
    },
    "Throes of Pain": {
        "total points required": 8,
        "allocated": 2,
        "max": 2,
        "unlocks": ["Translucent Image", "Cauterizing Shadows"],
        "parents": ["Void Shield", "San'layn", "Vampiric Embrace", "Apathy"],
        "mandatory": False,
    },
    "Angel's Mercy": {
        "total points required": 20,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Surge of Light", "Light's Inspiration"],
        "locks": "Binding Heals",
        "parents": ["Unwavering Will"],
        "mandatory": False,
    },
    "Binding Heals": {
        "total points required": 20,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Surge of Light", "Light's Inspiration"],
        "locks": "Angel's Mercy",
        "parents": ["Unwavering Will"],
        "mandatory": False,
    },
    "Divine Star": {
        "total points required": 20,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Light's Inspiration", "Crystalline Reflection"],
        "locks": "Halo",
        "parents": ["Unwavering Will", "Twist of Fate"],
        "mandatory": False,
    },
    "Halo": {
        "total points required": 20,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Light's Inspiration", "Crystalline Reflection"],
        "locks": "Divine Star",
        "parents": ["Unwavering Will", "Twist of Fate"],
        "mandatory": False,
    },
    "Translucent Image": {
        "total points required": 20,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Crystalline Reflection", "Improved Fade"],
        "parents": ["Twist of Fate", "Throes of Pain"],
        "mandatory": False,
    },
    "Cauterizing Shadows": {
        "total points required": 20,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Improved Fade", "Manipulation"],
        "parents": ["Throes of Pain"],
        "mandatory": False,
    },
    "Surge of Light": {
        "total points required": 20,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Benevolence", "Power Word: Life"],
        "parents": ["Angel's Mercy", "Binding Heals"],
        "mandatory": False,
    },
    "Light's Inspiration": {
        "total points required": 20,
        "allocated": 2,
        "max": 2,
        "unlocks": ["Benevolence", "Power Word: Life", "Angelic Bulwark"],
        "parents": ["Angel's Mercy", "Binding Heals", "Divine Star", "Halo"],
        "mandatory": False,
    },
    "Crystalline Reflection": {
        "total points required": 20,
        "allocated": 2,
        "max": 2,
        "unlocks": ["Angelic Bulwark", "Essence Devourer", "Void Shift"],
        "parents": ["Divine Star", "Halo", "Translucent Image"],
        "mandatory": False,
    },
    "Improved Fade": {
        "total points required": 20,
        "allocated": 2,
        "max": 2,
        "unlocks": ["Essence Devourer", "Void Shift", "Phantom Reach"],
        "parents": ["Translucent Image", "Cauterizing Shadows"],
        "mandatory": False,
    },
    "Manipulation": {
        "total points required": 20,
        "allocated": 1,
        "max": 1,
        "unlocks": ["Phantom Reach"],
        "parents": ["Cauterizing Shadows"],
        "mandatory": False,
    },
    "Benevolence": {
        "total points required": 20,
        "allocated": 1,
        "max": 1,
        "unlocks": [],
        "locks": "Power Word: Life",
        "parents": ["Surge of Light", "Light's Inspiration"],
        "mandatory": False,
    },
    "Power Word: Life": {
        "total points required": 20,
        "allocated": 1,
        "max": 1,
        "unlocks": [],
        "locks": "Benevolence",
        "parents": ["Surge of Light", "Light's Inspiration"],
        "mandatory": False,
    },
    "Angelic Bulwark": {
        "total points required": 20,
        "allocated": 1,
        "max": 1,
        "unlocks": [],
        "parents": ["Light's Inspiration", "Crystalline Reflection"],
        "mandatory": False,
    },
    "Essence Devourer": {
        "total points required": 20,
        "allocated": 1,
        "max": 1,
        "unlocks": [],
        "locks": "Void Shift",
        "parents": ["Crystalline Reflection", "Improved Fade"],
        "mandatory": False,
    },
    "Void Shift": {
        "total points required": 20,
        "allocated": 1,
        "max": 1,
        "unlocks": [],
        "locks": "Essence Devourer",
        "parents": ["Crystalline Reflection", "Improved Fade"],
        "mandatory": False,
    },
    "Phantom Reach": {
        "total points required": 20,
        "allocated": 1,
        "max": 1,
        "unlocks": [],
        "parents": ["Improved Fade", "Manipulation"],
        "mandatory": False,
    },
}
holypriest_spec_tree = {}
